# Yova Auto install engine - progress callbacks for GUI or console.
param(
  [string]$ProjectRoot = (Split-Path (Split-Path $PSScriptRoot -Parent) -Parent),
  [scriptblock]$OnProgress,
  [switch]$SilentLog
)

$SetupDir = Join-Path $ProjectRoot "setup"
$script:ProjectRoot = $ProjectRoot
$script:SetupSilent = [bool]$SilentLog

. (Join-Path $SetupDir "config.ps1")
. (Join-Path $SetupDir "scripts\_common.ps1")

function Send-Progress {
  param(
    [int]$Percent = -1,
    [string]$Message,
    [string]$StepId,
    [ValidateSet("pending", "running", "done", "error", "skipped")]
    [string]$StepState,
    [switch]$Indeterminate,
    [switch]$Complete,
    [switch]$Failed,
    [string]$ErrorDetail
  )
  if ($OnProgress) {
    & $OnProgress ([pscustomobject]@{
        Percent       = $Percent
        Message       = $Message
        StepId        = $StepId
        StepState     = $StepState
        Indeterminate = [bool]$Indeterminate
        Complete      = [bool]$Complete
        Failed        = [bool]$Failed
        ErrorDetail   = $ErrorDetail
      })
  }
}

function Write-StepLog([string]$msg) {
  Write-Log $msg
  if (-not $script:SetupSilent) {
    Write-Host "==> $msg" -ForegroundColor Cyan
  }
}

function Set-Step {
  param([string]$Id, [string]$Label, [int]$Percent)
  Send-Progress -StepId $Id -StepState "running" -Message $Label -Percent $Percent -Indeterminate
  Write-StepLog $Label
}

function Complete-Step([string]$Id, [string]$Message, [int]$Percent) {
  Send-Progress -StepId $Id -StepState "done" -Message $Message -Percent $Percent
}

function Write-EnvFile {
  param([string]$Path, [string[]]$Lines)
  $dir = Split-Path $Path -Parent
  if ($dir -and -not (Test-Path $dir)) {
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
  }
  Set-Content -Path $Path -Value ($Lines -join [Environment]::NewLine) -Encoding UTF8
}

function Write-LauncherBat {
  param([string]$Path, [string[]]$Lines)
  Set-Content -Path $Path -Value ($Lines -join [Environment]::NewLine) -Encoding ASCII
}

function Invoke-YovaAutoInstall {
  $stepIds = @("node", "sqlite", "config", "npm-frontend", "npm-backend", "build", "launchers", "startup", "shortcuts", "services")
  foreach ($id in $stepIds) {
    Send-Progress -StepId $id -StepState "pending" -Message $id -Percent 0
  }

  try {
    Set-Step "node" "Downloading portable Node.js..." 5
    Send-Progress -Indeterminate -Message "Downloading Node.js (may take a few minutes)..."
    & (Join-Path $SetupDir "scripts\install-node.ps1")
    Add-NodeToPath
    Complete-Step "node" "Node.js ready" 12

    Set-Step "sqlite" "Installing SQLite command-line tools..." 15
    Send-Progress -Indeterminate
    try {
      & (Join-Path $SetupDir "scripts\install-sqlite-tools.ps1")
      Complete-Step "sqlite" "SQLite tools installed" 18
    } catch {
      Send-Progress -StepId "sqlite" -StepState "skipped" -Message "SQLite tools skipped (optional)" -Percent 18
      Write-Log "SQLite tools: $($_.Exception.Message)" "WARN"
    }

    Set-Step "config" "Writing configuration files..." 22
    $date = Get-Date -Format "yyyy-MM-dd"
    $apiUrl = "http://127.0.0.1:$($SetupConfig.BackendPort)"
    Write-EnvFile -Path (Join-Path $ProjectRoot ".env") -Lines @(
      "# Generated by Yova Auto setup - $date"
      "VITE_API_URL=$apiUrl"
    )
    Write-EnvFile -Path (Join-Path (Join-Path $ProjectRoot "backend") ".env") -Lines @(
      "PORT=$($SetupConfig.BackendPort)"
    )
    Complete-Step "config" "Configuration saved" 25

    Set-Step "npm-frontend" "Installing frontend packages..." 28
    Send-Progress -Indeterminate -Message "npm install - frontend (please wait)..."
    Invoke-ProjectNpm -Arguments @("install") -WorkingDirectory $ProjectRoot
    Complete-Step "npm-frontend" "Frontend packages installed" 45

    Set-Step "npm-backend" "Installing backend packages..." 48
    Send-Progress -Indeterminate -Message "npm install - backend (please wait)..."
    Invoke-ProjectNpm -Arguments @("install") -WorkingDirectory (Join-Path $ProjectRoot "backend")
    Complete-Step "npm-backend" "Backend packages installed" 58

    Set-Step "build" "Building production frontend..." 62
    Send-Progress -Indeterminate -Message "Running production build..."
    $env:VITE_API_URL = $apiUrl
    Invoke-ProjectNpm -Arguments @("run", "build") -WorkingDirectory $ProjectRoot
    if (-not (Test-Path (Join-Path $ProjectRoot "dist"))) {
      throw "Build failed - dist folder not found. See setup\logs\yova-auto.log"
    }
    $serverIndex = Join-Path $ProjectRoot "dist\server\index.js"
    $serverPreview = Join-Path $ProjectRoot "dist\server\server.js"
    if (Test-Path $serverIndex) {
      Copy-Item $serverIndex $serverPreview -Force
      Write-Log "Created dist/server/server.js for vite preview"
    }
    Complete-Step "build" "Application built successfully" 72

    Set-Step "launchers" "Creating launcher scripts..." 75
    $startScript = Join-Path $SetupDir "scripts\start-yova.ps1"
    Write-LauncherBat -Path (Join-Path $ProjectRoot "YovaAuto-Start.bat") -Lines @(
      "@echo off"
      "title $($SetupConfig.AppName) - Starting"
      "cd /d `"$ProjectRoot`""
      "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$startScript`""
      "exit /b 0"
    )
    $openScript = Join-Path $SetupDir "scripts\open-app.ps1"
    Write-LauncherBat -Path (Join-Path $ProjectRoot "YovaAuto-Open.bat") -Lines @(
      "@echo off"
      "title $($SetupConfig.AppName)"
      "cd /d `"$ProjectRoot`""
      "powershell.exe -NoProfile -ExecutionPolicy Bypass -File `"$openScript`""
      "exit /b 0"
    )
    $bp = $SetupConfig.BackendPort
    $fp = $SetupConfig.FrontendPort
    Write-LauncherBat -Path (Join-Path $ProjectRoot "YovaAuto-Stop.bat") -Lines @(
      "@echo off"
      "title $($SetupConfig.AppName) - Stop"
      "echo Stopping processes on ports $bp and $fp..."
      "for /f `"tokens=5`" %%a in ('netstat -ano ^| findstr `":$bp `" ^| findstr LISTENING') do taskkill /F /PID %%a 2>nul"
      "for /f `"tokens=5`" %%a in ('netstat -ano ^| findstr `":$fp `" ^| findstr LISTENING') do taskkill /F /PID %%a 2>nul"
      "echo Done."
      "pause"
    )
    $statusBat = Join-Path $ProjectRoot "YovaAuto-Status.bat"
    $bt = $SetupConfig.BackendTaskName
    $ft = $SetupConfig.FrontendTaskName
    Write-LauncherBat -Path $statusBat -Lines @(
      "@echo off"
      "title $($SetupConfig.AppName) - Service Status"
      "echo."
      "echo === Scheduled tasks ==="
      "schtasks /Query /TN `"$bt`" /FO LIST 2>nul || echo   $bt : not registered"
      "echo."
      "schtasks /Query /TN `"$ft`" /FO LIST 2>nul || echo   $ft : not registered"
      "echo."
      "echo === Listening ports ==="
      "netstat -ano | findstr `":$bp `" | findstr LISTENING && echo   API ($bp): running || echo   API ($bp): stopped"
      "netstat -ano | findstr `":$fp `" | findstr LISTENING && echo   Web ($fp): running || echo   Web ($fp): stopped"
      "echo."
      "echo App URL: $($SetupConfig.AppUrl)"
      "echo."
      "pause"
    )
    Complete-Step "launchers" "Launchers created" 78

    Set-Step "startup" "Registering background services (Task Scheduler)..." 80
    & (Join-Path $SetupDir "scripts\register-autostart.ps1")
    Complete-Step "startup" "Background services registered" 85

    Set-Step "shortcuts" "Creating desktop shortcuts..." 88
    $desktop = [Environment]::GetFolderPath("Desktop")
    $urlLines = @(
      "[InternetShortcut]"
      "URL=$($SetupConfig.AppUrl)"
      "IconIndex=0"
    )
    Set-Content -Path (Join-Path $desktop "Yova Auto.url") -Value ($urlLines -join [Environment]::NewLine) -Encoding ASCII
    Copy-Item (Join-Path $ProjectRoot "YovaAuto-Open.bat") (Join-Path $desktop "Open Yova Auto.bat") -Force
    Complete-Step "shortcuts" "Desktop shortcuts created" 92

    $marker = @{
      installedAt  = (Get-Date).ToString("o")
      projectRoot  = $ProjectRoot
      appUrl       = $SetupConfig.AppUrl
      backendPort  = $SetupConfig.BackendPort
      frontendPort = $SetupConfig.FrontendPort
      defaultLogin = $SetupConfig.DefaultLogin
    } | ConvertTo-Json
    Set-Content -Path (Join-Path $SetupDir ".installed.json") -Value $marker -Encoding UTF8

    Set-Step "services" "Starting API and web interface..." 94
    Send-Progress -Indeterminate -Message "Starting services..."
    & $startScript
    Start-Sleep -Seconds 4
    Complete-Step "services" "Services running" 98

    Send-Progress -Percent 100 -Message "Setup complete!" -Complete -StepState "done"
    return @{ Ok = $true; AppUrl = $SetupConfig.AppUrl; Login = $SetupConfig.DefaultLogin }
  } catch {
    $err = $_.Exception.Message
    Write-Log $err "ERROR"
    Send-Progress -Failed -Message "Setup failed" -ErrorDetail $err -StepState "error"
    return @{ Ok = $false; Error = $err }
  }
}
