/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehiclesIndexRouteImport } from './routes/vehicles.index'
import { Route as QuotesIndexRouteImport } from './routes/quotes.index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices.index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as VehiclesVehicleIdRouteImport } from './routes/vehicles.$vehicleId'
import { Route as QuotesNewRouteImport } from './routes/quotes.new'
import { Route as QuotesQuoteIdRouteImport } from './routes/quotes.$quoteId'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as InvoicesInvoiceIdRouteImport } from './routes/invoices.$invoiceId'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as VehiclesVehicleIdIndexRouteImport } from './routes/vehicles.$vehicleId.index'
import { Route as QuotesQuoteIdIndexRouteImport } from './routes/quotes.$quoteId.index'
import { Route as CustomersCustomerIdIndexRouteImport } from './routes/customers.$customerId.index'
import { Route as VehiclesVehicleIdEditRouteImport } from './routes/vehicles.$vehicleId.edit'
import { Route as QuotesQuoteIdEditRouteImport } from './routes/quotes.$quoteId.edit'
import { Route as CustomersCustomerIdEditRouteImport } from './routes/customers.$customerId.edit'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIndexRoute = VehiclesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VehiclesRoute,
} as any)
const QuotesIndexRoute = QuotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuotesRoute,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRoute,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvoicesRoute,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersRoute,
} as any)
const VehiclesVehicleIdRoute = VehiclesVehicleIdRouteImport.update({
  id: '/$vehicleId',
  path: '/$vehicleId',
  getParentRoute: () => VehiclesRoute,
} as any)
const QuotesNewRoute = QuotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => QuotesRoute,
} as any)
const QuotesQuoteIdRoute = QuotesQuoteIdRouteImport.update({
  id: '/$quoteId',
  path: '/$quoteId',
  getParentRoute: () => QuotesRoute,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const InvoicesInvoiceIdRoute = InvoicesInvoiceIdRouteImport.update({
  id: '/$invoiceId',
  path: '/$invoiceId',
  getParentRoute: () => InvoicesRoute,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => CustomersRoute,
} as any)
const VehiclesVehicleIdIndexRoute = VehiclesVehicleIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VehiclesVehicleIdRoute,
} as any)
const QuotesQuoteIdIndexRoute = QuotesQuoteIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuotesQuoteIdRoute,
} as any)
const CustomersCustomerIdIndexRoute =
  CustomersCustomerIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CustomersCustomerIdRoute,
  } as any)
const VehiclesVehicleIdEditRoute = VehiclesVehicleIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => VehiclesVehicleIdRoute,
} as any)
const QuotesQuoteIdEditRoute = QuotesQuoteIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => QuotesQuoteIdRoute,
} as any)
const CustomersCustomerIdEditRoute = CustomersCustomerIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CustomersCustomerIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/quotes': typeof QuotesRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/vehicles': typeof VehiclesRouteWithChildren
  '/customers/$customerId': typeof CustomersCustomerIdRouteWithChildren
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/quotes/$quoteId': typeof QuotesQuoteIdRouteWithChildren
  '/quotes/new': typeof QuotesNewRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRouteWithChildren
  '/customers/': typeof CustomersIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/quotes/': typeof QuotesIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/customers/$customerId/edit': typeof CustomersCustomerIdEditRoute
  '/quotes/$quoteId/edit': typeof QuotesQuoteIdEditRoute
  '/vehicles/$vehicleId/edit': typeof VehiclesVehicleIdEditRoute
  '/customers/$customerId/': typeof CustomersCustomerIdIndexRoute
  '/quotes/$quoteId/': typeof QuotesQuoteIdIndexRoute
  '/vehicles/$vehicleId/': typeof VehiclesVehicleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/quotes/new': typeof QuotesNewRoute
  '/customers': typeof CustomersIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/quotes': typeof QuotesIndexRoute
  '/vehicles': typeof VehiclesIndexRoute
  '/customers/$customerId/edit': typeof CustomersCustomerIdEditRoute
  '/quotes/$quoteId/edit': typeof QuotesQuoteIdEditRoute
  '/vehicles/$vehicleId/edit': typeof VehiclesVehicleIdEditRoute
  '/customers/$customerId': typeof CustomersCustomerIdIndexRoute
  '/quotes/$quoteId': typeof QuotesQuoteIdIndexRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/quotes': typeof QuotesRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/vehicles': typeof VehiclesRouteWithChildren
  '/customers/$customerId': typeof CustomersCustomerIdRouteWithChildren
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/quotes/$quoteId': typeof QuotesQuoteIdRouteWithChildren
  '/quotes/new': typeof QuotesNewRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRouteWithChildren
  '/customers/': typeof CustomersIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/quotes/': typeof QuotesIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/customers/$customerId/edit': typeof CustomersCustomerIdEditRoute
  '/quotes/$quoteId/edit': typeof QuotesQuoteIdEditRoute
  '/vehicles/$vehicleId/edit': typeof VehiclesVehicleIdEditRoute
  '/customers/$customerId/': typeof CustomersCustomerIdIndexRoute
  '/quotes/$quoteId/': typeof QuotesQuoteIdIndexRoute
  '/vehicles/$vehicleId/': typeof VehiclesVehicleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/dashboard'
    | '/invoices'
    | '/jobs'
    | '/login'
    | '/quotes'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/vehicles'
    | '/customers/$customerId'
    | '/invoices/$invoiceId'
    | '/jobs/$jobId'
    | '/quotes/$quoteId'
    | '/quotes/new'
    | '/vehicles/$vehicleId'
    | '/customers/'
    | '/invoices/'
    | '/jobs/'
    | '/quotes/'
    | '/vehicles/'
    | '/customers/$customerId/edit'
    | '/quotes/$quoteId/edit'
    | '/vehicles/$vehicleId/edit'
    | '/customers/$customerId/'
    | '/quotes/$quoteId/'
    | '/vehicles/$vehicleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/invoices/$invoiceId'
    | '/jobs/$jobId'
    | '/quotes/new'
    | '/customers'
    | '/invoices'
    | '/jobs'
    | '/quotes'
    | '/vehicles'
    | '/customers/$customerId/edit'
    | '/quotes/$quoteId/edit'
    | '/vehicles/$vehicleId/edit'
    | '/customers/$customerId'
    | '/quotes/$quoteId'
    | '/vehicles/$vehicleId'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/dashboard'
    | '/invoices'
    | '/jobs'
    | '/login'
    | '/quotes'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/vehicles'
    | '/customers/$customerId'
    | '/invoices/$invoiceId'
    | '/jobs/$jobId'
    | '/quotes/$quoteId'
    | '/quotes/new'
    | '/vehicles/$vehicleId'
    | '/customers/'
    | '/invoices/'
    | '/jobs/'
    | '/quotes/'
    | '/vehicles/'
    | '/customers/$customerId/edit'
    | '/quotes/$quoteId/edit'
    | '/vehicles/$vehicleId/edit'
    | '/customers/$customerId/'
    | '/quotes/$quoteId/'
    | '/vehicles/$vehicleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  InvoicesRoute: typeof InvoicesRouteWithChildren
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  QuotesRoute: typeof QuotesRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  VehiclesRoute: typeof VehiclesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/': {
      id: '/vehicles/'
      path: '/'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof VehiclesIndexRouteImport
      parentRoute: typeof VehiclesRoute
    }
    '/quotes/': {
      id: '/quotes/'
      path: '/'
      fullPath: '/quotes/'
      preLoaderRoute: typeof QuotesIndexRouteImport
      parentRoute: typeof QuotesRoute
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRoute
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/customers/': {
      id: '/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/vehicles/$vehicleId': {
      id: '/vehicles/$vehicleId'
      path: '/$vehicleId'
      fullPath: '/vehicles/$vehicleId'
      preLoaderRoute: typeof VehiclesVehicleIdRouteImport
      parentRoute: typeof VehiclesRoute
    }
    '/quotes/new': {
      id: '/quotes/new'
      path: '/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof QuotesNewRouteImport
      parentRoute: typeof QuotesRoute
    }
    '/quotes/$quoteId': {
      id: '/quotes/$quoteId'
      path: '/$quoteId'
      fullPath: '/quotes/$quoteId'
      preLoaderRoute: typeof QuotesQuoteIdRouteImport
      parentRoute: typeof QuotesRoute
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/invoices/$invoiceId': {
      id: '/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof InvoicesInvoiceIdRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/vehicles/$vehicleId/': {
      id: '/vehicles/$vehicleId/'
      path: '/'
      fullPath: '/vehicles/$vehicleId/'
      preLoaderRoute: typeof VehiclesVehicleIdIndexRouteImport
      parentRoute: typeof VehiclesVehicleIdRoute
    }
    '/quotes/$quoteId/': {
      id: '/quotes/$quoteId/'
      path: '/'
      fullPath: '/quotes/$quoteId/'
      preLoaderRoute: typeof QuotesQuoteIdIndexRouteImport
      parentRoute: typeof QuotesQuoteIdRoute
    }
    '/customers/$customerId/': {
      id: '/customers/$customerId/'
      path: '/'
      fullPath: '/customers/$customerId/'
      preLoaderRoute: typeof CustomersCustomerIdIndexRouteImport
      parentRoute: typeof CustomersCustomerIdRoute
    }
    '/vehicles/$vehicleId/edit': {
      id: '/vehicles/$vehicleId/edit'
      path: '/edit'
      fullPath: '/vehicles/$vehicleId/edit'
      preLoaderRoute: typeof VehiclesVehicleIdEditRouteImport
      parentRoute: typeof VehiclesVehicleIdRoute
    }
    '/quotes/$quoteId/edit': {
      id: '/quotes/$quoteId/edit'
      path: '/edit'
      fullPath: '/quotes/$quoteId/edit'
      preLoaderRoute: typeof QuotesQuoteIdEditRouteImport
      parentRoute: typeof QuotesQuoteIdRoute
    }
    '/customers/$customerId/edit': {
      id: '/customers/$customerId/edit'
      path: '/edit'
      fullPath: '/customers/$customerId/edit'
      preLoaderRoute: typeof CustomersCustomerIdEditRouteImport
      parentRoute: typeof CustomersCustomerIdRoute
    }
  }
}

interface CustomersCustomerIdRouteChildren {
  CustomersCustomerIdEditRoute: typeof CustomersCustomerIdEditRoute
  CustomersCustomerIdIndexRoute: typeof CustomersCustomerIdIndexRoute
}

const CustomersCustomerIdRouteChildren: CustomersCustomerIdRouteChildren = {
  CustomersCustomerIdEditRoute: CustomersCustomerIdEditRoute,
  CustomersCustomerIdIndexRoute: CustomersCustomerIdIndexRoute,
}

const CustomersCustomerIdRouteWithChildren =
  CustomersCustomerIdRoute._addFileChildren(CustomersCustomerIdRouteChildren)

interface CustomersRouteChildren {
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRouteWithChildren
  CustomersIndexRoute: typeof CustomersIndexRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersCustomerIdRoute: CustomersCustomerIdRouteWithChildren,
  CustomersIndexRoute: CustomersIndexRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface InvoicesRouteChildren {
  InvoicesInvoiceIdRoute: typeof InvoicesInvoiceIdRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
}

const InvoicesRouteChildren: InvoicesRouteChildren = {
  InvoicesInvoiceIdRoute: InvoicesInvoiceIdRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
}

const InvoicesRouteWithChildren = InvoicesRoute._addFileChildren(
  InvoicesRouteChildren,
)

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRoute,
  JobsIndexRoute: JobsIndexRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface QuotesQuoteIdRouteChildren {
  QuotesQuoteIdEditRoute: typeof QuotesQuoteIdEditRoute
  QuotesQuoteIdIndexRoute: typeof QuotesQuoteIdIndexRoute
}

const QuotesQuoteIdRouteChildren: QuotesQuoteIdRouteChildren = {
  QuotesQuoteIdEditRoute: QuotesQuoteIdEditRoute,
  QuotesQuoteIdIndexRoute: QuotesQuoteIdIndexRoute,
}

const QuotesQuoteIdRouteWithChildren = QuotesQuoteIdRoute._addFileChildren(
  QuotesQuoteIdRouteChildren,
)

interface QuotesRouteChildren {
  QuotesQuoteIdRoute: typeof QuotesQuoteIdRouteWithChildren
  QuotesNewRoute: typeof QuotesNewRoute
  QuotesIndexRoute: typeof QuotesIndexRoute
}

const QuotesRouteChildren: QuotesRouteChildren = {
  QuotesQuoteIdRoute: QuotesQuoteIdRouteWithChildren,
  QuotesNewRoute: QuotesNewRoute,
  QuotesIndexRoute: QuotesIndexRoute,
}

const QuotesRouteWithChildren =
  QuotesRoute._addFileChildren(QuotesRouteChildren)

interface VehiclesVehicleIdRouteChildren {
  VehiclesVehicleIdEditRoute: typeof VehiclesVehicleIdEditRoute
  VehiclesVehicleIdIndexRoute: typeof VehiclesVehicleIdIndexRoute
}

const VehiclesVehicleIdRouteChildren: VehiclesVehicleIdRouteChildren = {
  VehiclesVehicleIdEditRoute: VehiclesVehicleIdEditRoute,
  VehiclesVehicleIdIndexRoute: VehiclesVehicleIdIndexRoute,
}

const VehiclesVehicleIdRouteWithChildren =
  VehiclesVehicleIdRoute._addFileChildren(VehiclesVehicleIdRouteChildren)

interface VehiclesRouteChildren {
  VehiclesVehicleIdRoute: typeof VehiclesVehicleIdRouteWithChildren
  VehiclesIndexRoute: typeof VehiclesIndexRoute
}

const VehiclesRouteChildren: VehiclesRouteChildren = {
  VehiclesVehicleIdRoute: VehiclesVehicleIdRouteWithChildren,
  VehiclesIndexRoute: VehiclesIndexRoute,
}

const VehiclesRouteWithChildren = VehiclesRoute._addFileChildren(
  VehiclesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRouteWithChildren,
  DashboardRoute: DashboardRoute,
  InvoicesRoute: InvoicesRouteWithChildren,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  QuotesRoute: QuotesRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  VehiclesRoute: VehiclesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
